config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'shortened_links#index'
  resources :shortened_links
  get '/s/*path' => 'shortened_links#translate'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shortened_link.rb
class ShortenedLink < ApplicationRecord
    UNIQUE_KEY_LENGTH = 5
    PREFIX = "http://localhost:3000/s/"

    # Validation
    validates :name, :original_url, :unique_key, :shortened_url, :hit_count, presence: true
    validates :original_url, uniqueness: {:case_sensitive => false, :message => ERROR_MSG[:LINK_EXIST]}
  
    # Check if shortened link exist
    def self.link_exist(orginial_url)
      !ShortenedLink.find_by_original_url(orginial_url).nil?
    end

    # Sanitize url
    def self.sanitize(url)
      url.strip!
      sanitized_url = url.downcase.gsub(/(https?:\/\/)|(www\.)/, "")
      sanitized_url = "http://#{sanitized_url}"
    end

    # Validate params and save it
    def self.validate_and_save(params)
      name = params[:name].strip
      original_url = params[:original_url].strip
      is_created = false
      message = ''

      if name.empty? || original_url.empty?
          message = ERROR_MSG[:EMPTY_DATA]
      else
          sanitized_url = sanitize(original_url)
          
          if !url_valid?(sanitized_url)
              message = ERROR_MSG[:INVALID_URL]
          elsif link_exist(sanitized_url)
              message = ERROR_MSG[:LINK_EXIST]
          else
              if generate(name, sanitized_url)
                  is_created = true
                  message = SUCCESS_MSG[:LINK_CREATED]
              else
                  message = ERROR_MSG[:ERROR]
              end
          end
      end
      [is_created, message]
    end

    # Generate short url and save it
    def self.generate(name, original_url)
      # Iterate until a unique key is found
      begin
        unique_key = self.generate_random_string(UNIQUE_KEY_LENGTH)
      end while ShortenedLink.find_by_unique_key unique_key
  
      sl = ShortenedLink.new
      sl.name = name
      sl.original_url = original_url
      sl.unique_key = unique_key
      sl.shortened_url = shortened_url(unique_key)
      sl.save
    end

    # Validate url
    def self.url_valid?(url)
      url = URI.parse(url) rescue false
      url.kind_of?(URI::HTTP) || url.kind_of?(URI::HTTPS)
    end 
  
    private
    # Returns shortened url from unique key
    def self.shortened_url(unique_key)
      PREFIX + unique_key
    end
  
    # generate a random string
    def self.generate_random_string(size)
      charset = ('a'..'z').to_a + (0..9).to_a
      (0...size).map{ charset.to_a[rand(charset.size)] }.join
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/shortened_links_controller.rb
class ShortenedLinksController < ApplicationController
    before_action :set_shortened_link, only: [:show, :edit, :update, :destroy]

    # GET /shortened_links
    def index
        @shortened_links = ShortenedLink.all
    end

    # GET /shortened_links/1
    def show
    end

    # GET /shortened_links/new
    def new
        @shortened_link = ShortenedLink.new
    end

    # GET /shortened_links/1/edit
    def edit
    end

    # POST /shortened_links
    def create
        is_created, message = ShortenedLink.validate_and_save(shortened_link_params)

        if is_created
            redirect_to shortened_links_url, notice: message
        else
            redirect_to new_shortened_link_url, notice: message
        end
    end

    # PATCH/PUT /shortened_links/1
    def update
        if shortened_link_params[:name].empty?
            redirect_to edit_shortened_link_url, notice: ERROR_MSG[:EMPTY_DATA]
        else
            if @shortened_link.update(shortened_link_params)
                redirect_to shortened_link_url, notice: SUCCESS_MSG[:NAME_UPDATED]
            else
                redirect_to edit_shortened_link_url, notice: ERROR_MSG[:ERROR]
            end
        end
    end

    # DELETE /shortened_links/1
    def destroy
        @shortened_link.destroy
        redirect_to shortened_links_url, notice: SUCCESS_MSG[:LINK_DESTROYED]
    end

    # GET /s/*
    def translate
        sl = ShortenedLink.find_by_unique_key(params[:path])

        if sl
            sl.hit_count += 1
            sl.save
            head :moved_permanently, :location => sl.original_url      
        else
            head :moved_permanently, :location => 'http://localhost:3000/shortened_links'
        end
    end

  private
    # Setting shortened link
    def set_shortened_link
      @shortened_link = ShortenedLink.find(params[:id])
    end

    # Restrict input parameters
    def shortened_link_params
      params.require(:shortened_link).permit(:id, :name, :original_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shortened_links_helper.rb
module ShortenedLinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>

    <%= yield %>
  </body>
</html>

app/views/shortened_links/edit.html.erb
<h1>Editing Shortened Link</h1>

<label>Name</label>
<label class="new-tab-label">Url</label>
<label class="new-tab-label2">Shortened Url</label>
<%= form_for @shortened_link, url: {action: "update"}, html: {class: "nifty_form"} do |f| %>
  <%= f.text_field :name %>
  <%= @shortened_link.original_url %>
  <%= @shortened_link.shortened_url %>
  <%= f.submit "Update" %>
<% end %>

<%= link_to 'Show', @shortened_link %>
<%= link_to 'Back', shortened_links_path %>

app/views/shortened_links/index.html.erb
<h1>Shortened Links</h1>

<% if flash[:success] -%>
  <p class='success'><%= flash[:success] %></p>
<% end -%>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Original Url</th>
      <th>Shortened Url</th>
      <th>Hit Counter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shortened_links.each do |shortened_link| %>
      <tr>
        <td><%= shortened_link.name %></td>
        <td><%= shortened_link.original_url %></td>
        <td><%= link_to shortened_link.shortened_url, shortened_link.shortened_url, target: :_blank %></td>
        <td><%= shortened_link.hit_count %></td>
        <td><%= link_to 'Show', shortened_link %></td>
        <td><%= link_to 'Edit', edit_shortened_link_path(shortened_link) %></td>
        <td><%= button_to 'Destroy', shortened_link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shortened Link', new_shortened_link_path %>

app/views/shortened_links/new.html.erb
<h1>New Shortened Link</h1>
<label>Name</label>
<label class="new-tab-label">Url</label>
<%= form_for @shortened_link, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :original_url %>
  <%= f.submit "Create" %>
<% end %>

<%= link_to 'Back', shortened_links_path %>

app/views/shortened_links/show.html.erb
<h1>Showing Shortened Link</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Original Url</th>
      <th>Shortened Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
    <td><%= @shortened_link.name %></td>
    <td><%= @shortened_link.original_url %></td>
    <td><%= link_to @shortened_link.shortened_url, @shortened_link.shortened_url %></td>
    </tr>
  </tbody>
</table>

<br/>
<%= link_to 'Edit', edit_shortened_link_path(@shortened_link) %> |
<%= link_to 'Back', shortened_links_path %>